# Generated by Django 5.2.17 on 2026-08-12 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_idempotancykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider', models.CharField(blank=True, choices=[('stripe', 'Stripe')], default='stripe', max_length=20, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='usd', max_length=3, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_order', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
