# Generated by Django 5.2.17 on 2026-08-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permissions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
